### ISSUE TITLE
这款机器的触摸板是可以驱动的

### ISSUE THREAD

**Issue by opensilence** [qine233/Lenovo-R7000-2021-Hackintosh#1]

**Comment by qine233** [comment]
我处理过了，但是并没有什么用，我不会弄这个

**Comment by opensilence** [comment]
![image](https://github.com/user-attachments/assets/831125a7-1a0f-4889-8eb7-b0a75cbb5cf2)
这个顺序

**Comment by qine233** [comment]
谢谢，我试一下
